### ISSUE TITLE
Network Usage display options

### ISSUE THREAD

**Issue by becauseim** [Kyome22/menubar_runcat#4]
RunCat is the best tiny app of its kind! 
I want to be able to display only the download speed in larger font, and without the Wi-Fi icon.
It'll look neater and more minimalistic.

**Comment by Kyome22** [comment]
@becauseim Is this issue for the App Store version?
If so, please use the issue report form of RunCat.app.
I have no plans to add network information to the RunCat OSS version.

**Comment by becauseim** [comment]
I do not understand you, unfortunately. Now when selecting the display speed indicator displays speed Internet connections up and down, but very small and poor print. For example I need only information about the speed down, it would be desirable to be able to show only her. It is planned in innovation? If yes, then you must install it AppStore version?

**Comment by Kyome22** [comment]
@becauseim 
The open source version of RunCat **does not have** the ability to display network information. The menubar_runcat and the App Store version of RunCat.app are different. menubar_runcat is a **reduced version** of the App Store version.

So, if you have a request for the App Store version, please use the issue report form (e-mail) instead of here.
